---
- name: restart amazon-cwa
  command: |
      amazon-cloudwatch-agent-ctl \
        -a append-config \
        -m ec2 \
        -c "file:{{ aws_cwa_dest_path }}/etc/cwa_metrics.json" \
        -s
  args:
      chdir: "{{ aws_cwa_dest_path }}/bin"
  become_method: sudo
  become: true